import { StyleSheet } from 'react-native';

export const createStyles = (backgroundColor: string, cardBackgroundColor: string, textColor: string, tintColor: string) =>
  StyleSheet.create({
    container: { flex: 1 },
    loadingContainer: { flex: 1, justifyContent: 'center', alignItems: 'center' },
    scrollView: { flex: 1, padding: 20 },
    title: { marginBottom: 30, textAlign: 'center' },
    section: { marginBottom: 25 },
    sectionTitle: { fontSize: 16, fontWeight: '600', marginBottom: 10, opacity: 0.8 },
    toggleContainer: {
      flexDirection: 'row',
      backgroundColor: cardBackgroundColor,
      borderRadius: 12,
      padding: 4,
      marginBottom: 25,
    },
    toggleButton: {
      flex: 1,
      paddingVertical: 12,
      paddingHorizontal: 20,
      borderRadius: 8,
      alignItems: 'center',
    },
    toggleButtonActive: { backgroundColor: tintColor },
    toggleButtonText: { fontSize: 16, fontWeight: '500' },
    toggleButtonTextActive: { color: backgroundColor },
    textArea: {
      backgroundColor: cardBackgroundColor,
      borderRadius: 12,
      padding: 15,
      fontSize: 16,
      color: textColor,
      minHeight: 100,
      textAlignVertical: 'top',
      marginBottom: 10,
    },
    pasteButton: {
      backgroundColor: tintColor,
      borderRadius: 8,
      paddingVertical: 12,
      paddingHorizontal: 20,
      alignItems: 'center',
      flexDirection: 'row',
      justifyContent: 'center',
      gap: 20,
    },
    pasteButtonText: { color: backgroundColor, fontSize: 16, fontWeight: '600' },
    typeContainer: { flexDirection: 'row', gap: 10 },
    typeButton: {
      flex: 1,
      backgroundColor: cardBackgroundColor,
      borderRadius: 12,
      paddingVertical: 15,
      paddingHorizontal: 20,
      alignItems: 'center',
      flexDirection: 'row',
      gap: 10,
      justifyContent: 'center',
    },
    typeButtonActive: { backgroundColor: tintColor },
    typeButtonText: { fontSize: 16, fontWeight: '500', color: textColor },
    typeButtonTextActive: { color: backgroundColor },
    input: {
      backgroundColor: cardBackgroundColor,
      borderRadius: 12,
      paddingVertical: 15,
      paddingHorizontal: 20,
      fontSize: 16,
      color: textColor,
    },
    placeholderColor: { color: textColor + '60' },
    categoryScroll: { flexGrow: 0 },
    categoryButton: {
      backgroundColor: cardBackgroundColor,
      borderRadius: 12,
      paddingVertical: 12,
      paddingHorizontal: 16,
      marginRight: 10,
      alignItems: 'center',
      minWidth: 80,
    },
    categoryButtonActive: { backgroundColor: tintColor },
    categoryIcon: { fontSize: 24, marginBottom: 4 },
    categoryButtonText: { fontSize: 12, fontWeight: '500', textAlign: 'center' },
    categoryButtonTextActive: { color: backgroundColor },
    paymentMethodContainer: { flexDirection: 'row', flexWrap: 'wrap', gap: 10 },
    paymentMethodButton: {
      backgroundColor: cardBackgroundColor,
      borderRadius: 12,
      paddingVertical: 12,
      paddingHorizontal: 16,
      flex: 1,
      flexDirection: 'row',
      minWidth: '45%',
      alignItems: 'center',
      justifyContent: 'flex-start',
      gap: 10,
    },
    paymentMethodButtonActive: { backgroundColor: tintColor },
    paymentMethodText: { fontSize: 14, fontWeight: '500', color: textColor },
    paymentMethodTextActive: { color: backgroundColor },
    dateTimeContainer: { flexDirection: 'row', gap: 10 },
    dateTimeButton: {
      flex: 1,
      backgroundColor: cardBackgroundColor,
      borderRadius: 12,
      paddingVertical: 15,
      paddingHorizontal: 20,
      alignItems: 'center',
      flexDirection: 'row',
      gap: 10,
      justifyContent: 'center',
    },
    dateTimeButtonText: { fontSize: 16, fontWeight: '500' },
    saveButton: {
      backgroundColor: tintColor,
      borderRadius: 12,
      paddingVertical: 18,
      alignItems: 'center',
      marginTop: 10,
      marginBottom: 20,
      flexDirection: 'row',
      gap: 10,
      justifyContent: 'center'
    },
    saveButtonText: { color: backgroundColor, fontSize: 18, fontWeight: '600' },
    bottomSpacing: { height: 20 },
  });
